apiVersion: policy/v1beta1  
kind: PodDisruptionBudget  
metadata:  
  name: blackbox-exporter
  namespace: monitoring 
  labels:
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/name: blackbox-exporter
spec:  
  minAvailable: 1
  selector:  
    matchLabels:  
      app.kubernetes.io/instance: blackbox
      app.kubernetes.io/name: blackbox-exporter