---
kind: Service
apiVersion: v1
metadata:
  name: tracing
  namespace: ingress-system
  labels:
    app: zipkin
spec:
  ports:
    - name: http-query
      protocol: TCP
      port: 80
      targetPort: 9411
  selector:
    app: zipkin
  type: ClusterIP
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  name: zipkin
  namespace: ingress-system
  labels:
    app: zipkin
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
  selector:
    app: zipkin
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zipkin
  namespace: ingress-system
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: "docker.io/openzipkin/zipkin:2.14.2"
          ports:
            - containerPort: 9411
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: QUERY_PORT
              value: "9411"
            - name: JAVA_OPTS
              value: |
                -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2
                -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
                -Xms700M -Xmx700M -XX:+UseG1GC -server
            - name: STORAGE_METHOD
              value: mem
            - name: ZIPKIN_STORAGE_MEM_MAXSPANS
              value: "500000"
          resources:
            limits:
              cpu: 300m
              memory: 900Mi
            requests:
              cpu: 150m
              memory: 900Mi
          livenessProbe:
            tcpSocket:
              port: 9411
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
              scheme: HTTP
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - s390x
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
