---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: ingress-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: ingress-system
  name: traefik
  labels:
    k8s-app: traefik
spec:
  selector:
    matchLabels:
      k8s-app: traefik
  template:
    metadata:
      labels:
        k8s-app: traefik
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: traefik
          image: traefik:v2.6.1
          args:
            - --api.insecure
            - --api.dashboard
            - --log
            - --log.level=INFO
            - --accesslog
            - --accessLog.fields.headers.defaultMode=redact
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --experimental.http3=true
            - --entrypoints.websecure.http3.advertisedport=443
            - --entryPoints.web.forwardedHeaders.insecure
            - --entryPoints.websecure.forwardedHeaders.insecure
            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowCrossNamespace=false
            - --providers.kubernetescrd.throttleDuration=10s
            - --providers.kubernetesingress=true
            - --providers.kubernetesingress.throttleDuration=10s
            - --metrics.prometheus
            - --serverstransport.insecureskipverify=true
            - --entrypoints.websecure.http.tls=true
            - --entrypoints.websecure.transport.respondingtimeouts.idletimeout=3600
            - --entryPoints.websecure.transport.respondingTimeouts.writeTimeout=3600
            - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=3600
            - --tracing.zipkin=true
            - --tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans
            - --tracing.zipkin.sameSpan=true
            - --tracing.zipkin.id128Bit=false
            - --tracing.zipkin.sampleRate=0.2
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: http3
              hostPort: 443
              containerPort: 443
              protocol: UDP
            - name: admin
              containerPort: 8080
              hostPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      #nodeSelector:
      #ingress: "yes"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/ingress
          operator: Equal
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: traefik
  name: traefik
  namespace: ingress-system
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 80
    - name: http3
      protocol: UDP
      port: 443
      targetPort: http3
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    k8s-app: traefik
