apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # true|false
  name: nfs-storage
  namespace: clusterstorage
mountOptions:
  - rw,nolock,tcp
  - vers=4
provisioner: fuseim.pri/ifs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
