kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zentao-pvc
  namespace: zentao 
  labels:
    k8s-app: zentao  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
