apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: traefik
  name: traefik
  namespace: ingress-system
spec:
  endpoints:
    - honorLabels: true
      interval: 15s
      port: admin
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: traefik
